### PR TITLE
Turn off dispersion correction.

### PR DESCRIPTION
**Pull request by ctk3b**
And match the vdW cutoff radii.

Is there any reason we want this to be on?

### CODE REVIEW

**Comment by mrshirts** [comment]
Cutoffs are frequently implemented differently.  Implementing a dispersion
correction is more likely to be consistent. Also, I'm not sure desmond has
direct cutoffs.

**Comment by mrshirts** [comment]
What are the specific problems that this would solve?

**Comment by ctk3b** [comment]
It improved agreement for the lj3 test during G->L but since it doesn't match perfectly, I'll see if I can't find out what's causing the rest of the discrepancies first.

**Comment by mrshirts** [comment]
Yeah, thats probably a little lower priority, it will require getting into
the weeds of implementations (which we will need to do, but that's the next
pass, and I know those details better).  We have to deal with this sort of
issue with the water box as well.

**Comment by ctk3b** [comment]
Alright then I'll leave this alone for now. 

For the record: adding tail corrections to LAMMPS brings the agreement in the LJ test from 43.6 down to 0.0225. However, it also increases differences in systems that were ~1e-6 - 1e-7 up to 0.0006.

**Comment by ctk3b** [comment]
Closing until we resolve #223

**Pull request closed without merging**
