### PR TITLE
Remove `record_exception`

### PR DESCRIPTION
**Pull request by ctk3b**

### CODE REVIEW

**Comment by mrshirts** [comment]
Do you want to check with Ellen on why this was set up the way it was?  IIRC (can't check right now) it was to make sure that the exceptions get written to the debug file rather than being printed to the screen.

**Comment by ctk3b** [comment]
It was. Per the brief discussion in #250, I think we want to throw errors a bit more explicitly. With this change they still get written to the log file but the summary will just say "converted" if the energy evaluation failed somewhere.

**Comment by mrshirts** [comment]
Hmm. a message of "converted" is not quite the message we want to send -- if there was a failure, then there probably should be some sort of "converted, but energy evaluation failed", prompting a user to go look at the full file.

**Comment by ctk3b** [comment]
You're absolutely right. Getting a little ahead of myself here trying to tidy up the error reporting.

**Pull request merged**
