### PR TITLE
Lammps to Gromacs: Include Cvff Improper Style and OPLS dihedral 

### PR DESCRIPTION
**Pull request by Jeet-Majumdar**
Set the last column of LAMMPS OPLS dihedral coefficient to 0, and parse LAMMPS cvff improper.

### CODE REVIEW

**Comment by mattwthompson** [comment]
Hi @Jeet-Majumdar, thanks for the contribution! It looks like some of the files you added shouldn't be included - `build/` `dist`/, `intermol.egg-info` - could you remove those files from tracking? You probably ran `git add .` which can work fine in some situations, but these files are just the local install on your machine and don't need to be tracked in the repo.

I'll update the `.gitignore` to be more helpful here as well

**Comment by Jeet-Majumdar** [comment]
Hi @mattwthompson,  yes, it was also looking weird to me as well. You were right. I ran `git add .` Updated in the new commit. Thanks!

**Comment by mattwthompson** [comment]
Thanks!

**Comment by Jeet-Majumdar** [comment]
Hi @mattwthompson, can this PR be merged?
Thanks

**Pull request closed without merging**
