### PR TITLE
Bundle units package from ParmEd/simtk

### PR DESCRIPTION
**Pull request by swails**
If ParmEd is available, just import the units package contents from there. This
way, it should work seamlessly with ParmEd when the time comes to do so.

Sample implementation for [my comment](https://github.com/shirtsgroup/InterMol/pull/246#issuecomment-134616382) in #246

### CODE REVIEW

**Comment by mrshirts** [comment]
I'm a little paranoid about copying large chunks of code, especially if we start merging later.  I think it might be better to just install the updated simtk.unit package in conda , and then switch over to something like this when we start importing paramed into InterMol for other things anyway.

**Comment by swails** [comment]
The main reason I did this is that the standalone `simtk.unit` package is really not ever updated to my knowledge.  It was split off from OpenMM, but a lot of people don't know (or forget) it exists, in my experience.

Maybe that's changed, but I avoid that package since that was the attitude last time we discussed it.

**Comment by swails** [comment]
Not ever is probably unfair, but it's certainly not well-maintained.

**Comment by mrshirts** [comment]
OK, we'll think about the best strategy.  Until we start distributing widely, then it probably doesn't matter so much.

**Pull request closed without merging**
