### PR TITLE
reorder atom_orders starting from best match (#312)

### PR DESCRIPTION
**Pull request by maaren**
With this patch pyrrole works for me

### CODE REVIEW

**Comment by ctk3b** [comment]
This looks good to me for now. Can we precisely emulate the resolution order used in GROMACS? Do you have a link to that source code?

**Comment by maaren** [comment]
According to David: The corresponding gromacs source code would be gmxpreprocess/toppush.cpp,
function  natom_match

**Comment by dspoel** [comment]
The corresponding gromacs source code would be gmxpreprocess/toppush.cpp, function natom_match

**Comment by ctk3b** [comment]
Great thank you. I'll merge for now and then make sure we're precisely replicating the behavior with no edge cases.

**Pull request merged**
