### PR TITLE
[WIP] Conda build on Travis.

### PR DESCRIPTION
**Pull request by ctk3b**

### CODE REVIEW

**Comment by mrshirts** [comment]
Let me know what should do to test this (when you're ready).

**Comment by ctk3b** [comment]
One annoying thing right now is that I can't find `simtk.unit` anywhere on conda as a standalone package. I'm going to use the openmm package for now just to see if I can get it to work but we'll probably want a workaround for this. This was discussed on the openmm issues a while ago but I don't think anything ever came of it...

**Comment by ctk3b** [comment]
I'm running into some issues related to the folder management of the tests and them not getting properly copied into the conda build directory. Should we maybe hold off on this for a bit anyways since early users will definitely want to play with the tests? Conda installing would be more for an end user.

**Comment by mrshirts** [comment]
I think that's fine for now.  It would be nice to get working, but doesn't
need to be immediate.

**Comment by mrshirts** [comment]
Is there an action item on this that I can take care of?

**Pull request closed without merging**
