### PR TITLE
Minor fixes in exclusions.py.

### PR DESCRIPTION
**Pull request by ctk3b**

### CODE REVIEW

**Comment by mrshirts** [comment]
What was the bug here?

**Comment by ctk3b** [comment]
No bug, mostly code style. `__repr__` and `__str__` should return, not print and `isinstance` is the preferred way to check types .

**Comment by mrshirts** [comment]
Sure, as long as it runs correctly.

**Comment by ctk3b** [comment]
All the unit tests run locally for me. If this breaks something, we have more serious issues :)

**Comment by swails** [comment]
Actually, I think the `__repr__` and `__str__` *were* bugs.  I don't think they're allowed to return `None`

```Python
In [3]: class SomeClass(object):
   ...:     def __repr__(self):
   ...:         print('Inside __repr__')
   ...:     def __str__(self):
   ...:         print('Inside __str__')
   ...:         

In [4]: x = SomeClass()

In [5]: x
Inside __repr__
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/iscratch/miniconda/2/envs/py27_1/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
    688                 type_pprinters=self.type_printers,
    689                 deferred_pprinters=self.deferred_printers)
--> 690             printer.pretty(obj)
    691             printer.flush()
    692             return stream.getvalue()

/iscratch/miniconda/2/envs/py27_1/lib/python2.7/site-packages/IPython/lib/pretty.pyc in pretty(self, obj)
    405                             if callable(meth):
    406                                 return meth(obj, self, cycle)
--> 407             return _default_pprint(obj, self, cycle)
    408         finally:
    409             self.end_group()

/iscratch/miniconda/2/envs/py27_1/lib/python2.7/site-packages/IPython/lib/pretty.pyc in _default_pprint(obj, p, cycle)
    525     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
    526         # A user-provided repr. Find newlines and replace them with p.break_()
--> 527         _repr_pprint(obj, p, cycle)
    528         return
    529     p.begin_group(1, '<')

/iscratch/miniconda/2/envs/py27_1/lib/python2.7/site-packages/IPython/lib/pretty.pyc in _repr_pprint(obj, p, cycle)
    707     """A pprint that just redirects to the normal repr function."""
    708     # Find newlines and replace them with p.break_()
--> 709     output = repr(obj)
    710     for idx,output_line in enumerate(output.splitlines()):
    711         if idx:

TypeError: __repr__ returned non-string (type NoneType)
```

As for the type checking, `isinstance` is a better choice, since it works with inheritance.

**Pull request merged**
