### PR TITLE
Added angle type 10 and dihedral types 10 and 11 in gromacs + some logic cleanup

### PR DESCRIPTION
**Pull request by mrshirts**

### CODE REVIEW

**Comment by mrshirts** [comment]
Addresses issue #132

**Comment by ctk3b** [comment]
The new force classes are missing.

**Comment by mrshirts** [comment]
I thought we were going to have the setup.py build them automatically?

**Comment by ctk3b** [comment]
Yes but it hasn't been set up yet.

**Comment by mrshirts** [comment]
Added.

**Comment by ctk3b** [comment]
I'm going to merge this and pull it into #224

**Comment by ctk3b** [comment]
These tests don't seem to be valid in 5.0.5. Is this an obvious fix or should I start digging? 

```
grompp_d -f ../../grompp.mdp -c dihedral10.gro -p dihedral10.top
GROMACS:    gmx grompp, VERSION 5.0.5 (double precision)

GROMACS is written by:
Emile Apol         Rossen Apostolov   Herman J.C. Berendsen Par Bjelkmar       
Aldert van Buuren  Rudi van Drunen    Anton Feenstra     Sebastian Fritsch  
Gerrit Groenhof    Christoph Junghans Peter Kasson       Carsten Kutzner    
Per Larsson        Justin A. Lemkul   Magnus Lundborg    Pieter Meulenhoff  
Erik Marklund      Teemu Murtola      Szilard Pall       Sander Pronk       
Roland Schulz      Alexey Shvetsov    Michael Shirts     Alfons Sijbers     
Peter Tieleman     Christian Wennberg Maarten Wolf       
and the project leaders:
Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2014, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, VERSION 5.0.5 (double precision)
Executable:   /usr/local/gromacs/bin/gmx_d
Library dir:  /usr/local/gromacs/share/gromacs/top
Command line:
  grompp_d -f ../../grompp.mdp -c dihedral10.gro -p dihedral10.top -maxwarn 5


Back Off! I just backed up mdout.mdp to ./#mdout.mdp.6#

NOTE 1 [file ../../grompp.mdp]:
  The group cutoff scheme is deprecated in Gromacs 5.0 and will be removed
  in a future release when all interaction forms are supported for the
  verlet scheme. The verlet scheme already scales better, and it is
  compatible with GPUs and other accelerators.


NOTE 2 [file ../../grompp.mdp]:
  The Berendsen thermostat does not generate the correct kinetic energy
  distribution. You might want to consider using the V-rescale thermostat.

Setting the LD random seed to 2193814107

ERROR 1 [file dihedral10.top, line 27]:
  Incorrect number of atomtypes for dihedral (4 instead of 2 or 4)


ERROR 2 [file dihedral10.top, line 28]:
  Incorrect number of atomtypes for dihedral (4 instead of 2 or 4)


ERROR 3 [file dihedral10.top, line 29]:
  Incorrect number of atomtypes for dihedral (4 instead of 2 or 4)


ERROR 4 [file dihedral10.top, line 30]:
  Incorrect number of atomtypes for dihedral (4 instead of 2 or 4)

Generated 10 of the 10 non-bonded parameter combinations
Generating 1-4 interactions: fudge = 0.5
Generated 10 of the 10 1-4 parameter combinations

ERROR 5 [file dihedral10.top, line 92]:
  No default Restricted Dih. types


ERROR 6 [file dihedral10.top, line 93]:
  No default Restricted Dih. types


ERROR 7 [file dihedral10.top, line 94]:
  No default Restricted Dih. types


ERROR 8 [file dihedral10.top, line 95]:
  No default Restricted Dih. types


ERROR 9 [file dihedral10.top, line 96]:
  No default Restricted Dih. types


ERROR 10 [file dihedral10.top, line 97]:
  No default Restricted Dih. types


ERROR 11 [file dihedral10.top, line 98]:
  No default Restricted Dih. types


ERROR 12 [file dihedral10.top, line 99]:
  No default Restricted Dih. types


ERROR 13 [file dihedral10.top, line 100]:
  No default Restricted Dih. types


ERROR 14 [file dihedral10.top, line 101]:
  No default Restricted Dih. types


ERROR 15 [file dihedral10.top, line 102]:
  No default Restricted Dih. types

Excluding 3 bonded neighbours molecule type 'Ethanol'

There were 2 notes

-------------------------------------------------------
Program grompp_d, VERSION 5.0.5
Source code file: /Users/ctk3b/builds/gromacs-5.0.5/src/gromacs/gmxpreprocess/grompp.c, line: 1724

Fatal error:
There were 15 errors in input file(s)
For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------
```

**Comment by mrshirts** [comment]
There was a problem with gromacs where types 10 and 11 were misdocumented.

However, I'm discovering some more issues (in gromacs itself).

Not sure why my previous checks passed, am looking into this more.

**Comment by mrshirts** [comment]
See the gromacs redmine for the issues.  I think these must be
misimplemented in gromacs given the output.  Again, not sure why the test I
ran last night passed  - I must have misinterpreted it.  I removed the
dihedral tests for now.

**Pull request merged**
