### PR TITLE
Improve LAMMPS ==> GROMACS conversion

### PR DESCRIPTION
**Pull request by jpthompson17**
I made some changes mainly geared toward conversion from LAMMPS to GROMACS. Key changes include the following:
- Read/write multiple molecules/molecule types in lammps_parser.py. Unique molecule types are detected using the (not rigorous but usually sufficient) method employed in the TopoTools VMD plugin (see topogromacs.tcl).
- Infer 1-4 interactions topologically to properly generate [ pairs ] in GROMACS topologies.
- Detect rigid 3-site waters and define SETTLE constraints.
- Add support for reading additional dihedral styles (fourier, multi/harmonic) and improper styles (cvff).

### CODE REVIEW

**Comment by mrshirts** [comment]
Thanks so much for contributing!  We've been plugging slowly along, and would love to have some more help to get this important project to the point that many people can use it. 

One issue I want to check with you on -- over the last couple months, we have been moving forward with the develop branch, because we had to reengineer much of the architecture to make it more extensible.

Would it be possible to take a look at the develop branch and see if the pull request can be made there?  I realize 1) there will be a number of changes because the code has changed and 2) this is a lot to ask, but if you were able to, that would help us with the reorganization immensely.  We can help coordinate if that will be necessary to make it happen. 

Again, we greatly appreciate your contributions to and interest in the project!

**Comment by jpthompson17** [comment]
Sure. I'll take a look at the develop branch and see what needs to be changed (perhaps some of the changes I made have already been made on your end). I'll aim to submit a pull request in the next day or two.

**Comment by mrshirts** [comment]
And talking to Christoph, there are a couple of things that are being included in the features/lammps case that might be merged in soon.  Christoph, can you confirm? Should Jeff wait until that branch is merged into develop to add his changes?

**Comment by ctk3b** [comment]
The feature/lammps branch is the one where I was fixing up the lammps parser. I'm hoping to knock out a few things that came up yesterday and then I'll just merge em.

**Comment by jpthompson17** [comment]
I noticed that the LAMMPS-related code was being worked on in the feature/lammps branch and took a look at it to see what had changed since a couple months ago. Christoph, should l wait until you merge feature/lammps into develop, then sync and make changes?

**Comment by ctk3b** [comment]
I've just gone ahead and merged it. This will be simpler for now. The big issue with the lammps code write now is #149. Once that's working I hope many of the unit tests will convert correctly which gives us a bunch of "free" tests to use for Lammps->XXX conversion.

**Comment by ctk3b** [comment]
Also I figured I'd give gitter a try. I'll be on here for the rest of the night if you have any questions: https://gitter.im/shirtsgroup/InterMol

**Pull request closed without merging**
