### PR TITLE
revamped intermol.forces, removing code generation

### PR DESCRIPTION
**Pull request by sallai**

### CODE REVIEW

**Comment by mrshirts** [comment]
Wait -- can we clarify _why_ the code generation was removed? the goal was to make it possible to describe just the parameters of the interaction, and then let the code do all the hard work of writing the interfaces.  The description here is definitely insufficient.

**Comment by mrshirts** [comment]
Or are you just saying you removed the code which is autogenerated? (which makes sense).

**Comment by ctk3b** [comment]
We're going back on this idea anyways but just to document some of the offline discussion from yesterday, the attempt here was to move the logic in `forcefunctions.py` into the actual forcetypes and pull the information from the decorators and `__slots__`. This looked like it would *probably* work except for the issue of some simulators specifying parameters in different orders. Once we started talking about patching that issue, the current approach started looking like a better choice again.

**Comment by mrshirts** [comment]
OK, thanks for the heads up!

**Pull request merged**
