### PR TITLE
Refactor testing code.

### PR DESCRIPTION
**Pull request by ctk3b**
Consolidates all testing functions into `test_all.py` which serves both as an entry point for local testing and contains all of the functions tested by py.test.

Also fixes tabs/spaces issue in `constraint.py`

Resolves: #157, #170

### CODE REVIEW

**Comment by mrshirts** [comment]
Should I start testing this now or wait?

**Comment by ctk3b** [comment]
Probably not worth it just yet.

**Comment by ctk3b** [comment]
This should be good to test now. To run locally, use `python test_all.py -t unit -p gromacs -e`. Same as before, except one script with an added flag `-p, --program` which can be any of the supported engines.

**Comment by mrshirts** [comment]
When energy calculations are turned off, we get a final report of the form:

    All unit tests for GROMACS to GROMACS match within 1.0e-04 kJ/mol.
    All unit tests for GROMACS to LAMMPS match within 1.0e-04 kJ/mol.
    All unit tests for GROMACS to DESMOND match within 1.0e-04 kJ/mol.

Which doesn't make sense, since no energy test is run.

Also, i would suggest double precision by default for gromacs tests; it makes it easier to see what is a rounding error and what is a bug.  We should figure out if that's easier to let users to, or to set automatically.

**Comment by mrshirts** [comment]
When running python test_all.py -t unit -e, it hits an exception after the gromacs calls, with 

Exception: GROMACS to GROMACS unit tests do not match within 1.0e-04 kJ/mol.

When I think we want to keep going.

**Comment by mrshirts** [comment]
For several gromacs to lammps tests, getting the error:

   INFO 2015-08-03 11:27:59 Evaluating energy of    /Users/mrshirts/work/papers/MMTOOLS/InterMol_original/intermol/tests/unit_test_outputs/from_gromacs/angle2/angle2_converted.input
ERROR 2015-08-03 11:27:59 global name 'FileNotFoundError' is not defined
Traceback (most recent call last):
  File "/Users/mrshirts/work/papers/MMTOOLS/InterMol_original/intermol/convert.py", line 216, in main
    '{0}.input'.format(oname), lmppath=lmppath)
  File "/Users/mrshirts/work/papers/MMTOOLS/InterMol_original/intermol/lammps/lammps_driver.py", line 41, in lammps_energies
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

**Comment by ctk3b** [comment]
> Also, i would suggest double precision by default for gromacs tests; it makes it easier to see what is a rounding error and what is a bug. We should figure out if that's easier to let users to, or to set automatically.

Right now it [tries to use double precision](https://github.com/shirtsgroup/InterMol/blob/develop/intermol/gromacs/gromacs_driver.py#L69) binaries first and only uses single if it cannot find them.

**Comment by ctk3b** [comment]
> When running python test_all.py -t unit -e, it hits an exception after the gromacs calls, with
```Exception: GROMACS to GROMACS unit tests do not match within 1.0e-04 kJ/mol.```
When I think we want to keep going.

This should be resolved with 2303a6c

**Comment by ctk3b** [comment]
Could you give me more information about the following? That particular test does not fail for me and it matches to within ~2e-07. 

> For several gromacs to lammps tests, getting the error:

> INFO 2015-08-03 11:27:59 Evaluating energy of /Users/mrshirts/work/papers/MMTOOLS/InterMol_original/intermol/tests/unit_test_outputs/from_gromacs/angle2/angle2_converted.input
ERROR 2015-08-03 11:27:59 global name 'FileNotFoundError' is not defined
Traceback (most recent call last):
File "/Users/mrshirts/work/papers/MMTOOLS/InterMol_original/intermol/convert.py", line 216, in main
'{0}.input'.format(oname), lmppath=lmppath)
File "/Users/mrshirts/work/papers/MMTOOLS/InterMol_original/intermol/lammps/lammps_driver.py", line 41, in lammps_energies
except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

My output right now is:

```
Results for GROMACS to LAMMPS Conversion
=========================================
Input File   Status/Potential Energy Diff
-----------------------------------------
angle1              3.266200003793074e-07
angle2              2.288890037505098e-07
angle3       CrossBondBondAngle is not supported by LAMMPS!
angle4       CrossBondAngleAngle is not supported by LAMMPS!
angle5                 0.0686834708710009
angle6       QuarticAngle is not supported by LAMMPS!
bond1               1.334469992286813e-07
bond2        G96Bond is not supported by LAMMPS!
bond3             -2.6102100036951015e-07
bond4        CubicBond is not supported by LAMMPS!
bond5        ConnectionBond conversion has not yet been implemented in InterMol.
bond6                  -668726.0645863333
bond7        FeneBond conversion has not yet been implemented in InterMol.
dihedral1           5.331750045911576e-07
dihedral2          3.1620288609701674e-09
dihedral3          3.1643400433267743e-07
dihedral4         -1.3615139664580056e-06
dihedral5          2.1363659996609385e-06
dihedral9           4.076340246683685e-06
lj3          Unable to read LAMMPS energy output
pairs1                  -808.163605330669
spce1                   9397431.406078989
spce2               0.0016062839350006186
virtual21    Unable to read LAMMPS energy output
virtual31    Unable to read LAMMPS energy output
virtual32    Unable to read LAMMPS energy output
virtual33    Unable to read LAMMPS energy output
virtual34    Unable to read LAMMPS energy output
virtual42    Unable to read LAMMPS energy output
```

**Comment by mrshirts** [comment]
What appears to be happening is that it is trying to remove lammps_stdout.txt, which for whatever reason does not exist.  If it's a fresh installation, for example, it wouldn't exist already.  But the error might be confusing to show up in the logfile.

**Comment by ctk3b** [comment]
Huh that should be getting raised. The code is here: https://github.com/shirtsgroup/InterMol/blob/develop/intermol/lammps/lammps_driver.py#L39

**Comment by ctk3b** [comment]
Oh I see the problem. `FileNotFoundError` is not built-in in python2.

**Comment by ctk3b** [comment]
3ab2850 should fix this for now. Ultimately it might be better to capture the LAMMPS output within python and then overwriting whatever file exists instead of reading the energies from the file.

**Comment by mrshirts** [comment]
Seems to check out.  Any reason I shoudn't merge now?

**Comment by ctk3b** [comment]
I think it's good to go!

**Pull request merged**
